package com.acerbisgianluca.ganttproject.gui;

import com.acerbisgianluca.filemanager.FileManager;
import com.acerbisgianluca.ganttproject.exceptions.CannotCheckVersionException;
import com.acerbisgianluca.ganttproject.exceptions.TaskAlreadyExistsException;
import com.acerbisgianluca.ganttproject.exceptions.TaskNotFoundException;
import com.acerbisgianluca.ganttproject.utilities.Algorithm;
import com.acerbisgianluca.ganttproject.utilities.Task;
import com.acerbisgianluca.ganttproject.utilities.VersionManager;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.function.Function;
import javafx.scene.control.DatePicker;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * E' la classe principale che non viene instanziata e che contiene i metodi
 * principali. Gestisce tutta la comunicazione con l'utente raccogliendo tutti i
 * dati sulle attività.
 *
 * @author Gianluca
 */
public class App extends javax.swing.JFrame {

    /**
     * Il modello della tabella.
     */
    private final DefaultTableModel tableModel;
    /**
     * Il modello della lista di possibili dipendenze.
     */
    private final DefaultListModel<String> listModel;
    /**
     * L'oggetto che contiene i metodi per eseguire l'algoritmo.
     */
    private Algorithm algorithm;
    /**
     * Indica se si sta modificando un
     * {@link com.acerbisgianluca.ganttproject.utilities.Task} già esistente.
     */
    private boolean editing;
    /**
     * Il nome precedente del
     * {@link com.acerbisgianluca.ganttproject.utilities.Task} che si sta
     * modificando.
     */
    private String lastName;
    /**
     * Formattatore per le date da stringa a oggetto e viceversa.
     */
    private final DateTimeFormatter fmt;
    /**
     * Filtro per le estensioni dei file.
     */
    private final FileNameExtensionFilter fileNameExtensionFilter;

    private boolean isAdvanced;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        this.tableModel = (DefaultTableModel) table.getModel();
        this.listModel = new DefaultListModel<>();
        this.listDependencies.setModel(listModel);
        this.algorithm = new Algorithm();
        this.editing = false;
        this.fmt = DateTimeFormatter.ofPattern("dd/MMM/yyyy");
        this.fileNameExtensionFilter = new FileNameExtensionFilter("Gantt project (*.gantt)", "gantt");
        cleanFields(true);
        setRowSorter();
        this.isAdvanced = false;
        toggleAdvanced();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        lblAddTask = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        spnDuration = new javax.swing.JSpinner();
        lblStartDate = new javax.swing.JLabel();
        spnDate = new javax.swing.JSpinner();
        lblDependencies = new javax.swing.JLabel();
        listScrollPane = new javax.swing.JScrollPane();
        listDependencies = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnDeleteTask = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblOutput = new javax.swing.JLabel();
        toggleAdvanced = new javax.swing.JToggleButton();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        spnA = new javax.swing.JSpinner();
        lblM = new javax.swing.JLabel();
        spnM = new javax.swing.JSpinner();
        lblB = new javax.swing.JLabel();
        spnB = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        lblPublicHolidays = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPublicHolidays = new javax.swing.JList<>();
        btnPublicDays = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        btnSave = new javax.swing.JMenuItem();
        btnLoad = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        github = new javax.swing.JMenuItem();
        tutorial = new javax.swing.JMenuItem();
        bugReport = new javax.swing.JMenuItem();
        btnCheckUpdate = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gantt Project");
        setResizable(false);

        lblAddTask.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddTask.setText("Aggiungi una nuova attività");

        lblName.setText("Nome");

        lblDuration.setText("Durata");

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblStartDate.setText("Data di inizio");

        spnDate.setModel(new javax.swing.SpinnerDateModel());

        lblDependencies.setText("Precedenze");

        listScrollPane.setViewportView(listDependencies);

        btnAdd.setText("Aggiungi");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDeleteTask.setText("Elimina attività");
        btnDeleteTask.setEnabled(false);
        btnDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTaskActionPerformed(evt);
            }
        });

        btnDeleteAll.setText("Elimina tutto");
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Durata", "Early Start", "Early Finish", "Late Start", "Late Finish", "Critica", "ET", "SD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setDragEnabled(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        tableScrollPane.setViewportView(table);

        lblOutput.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        toggleAdvanced.setText("Mod. avanzata");
        toggleAdvanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleAdvancedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAddTask)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                            .addComponent(lblName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblDuration)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblStartDate)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(spnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDependencies))
                                        .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteTask)
                            .addComponent(btnDeleteAll)
                            .addComponent(toggleAdvanced))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddTask)
                .addGap(10, 10, 10)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName)
                            .addComponent(lblDuration)
                            .addComponent(spnDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStartDate)
                            .addComponent(lblDependencies)
                            .addComponent(spnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteTask)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDeleteAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toggleAdvanced)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(listScrollPane))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Modalità avanzata");

        lblA.setText("Tempo ottimale");

        spnA.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblM.setText("Tempo probabile");

        spnM.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblB.setText("Tempo peggiore");

        spnB.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lblPublicHolidays.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPublicHolidays.setText("Giorni festivi");

        listPublicHolidays.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPublicHolidays);

        btnPublicDays.setText("Imposta");
        btnPublicDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPublicDaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnM, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblPublicHolidays)
                                    .addComponent(btnPublicDays))
                                .addGap(0, 28, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblA)
                    .addComponent(spnA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblM)
                    .addComponent(spnM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB)
                    .addComponent(spnB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPublicHolidays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPublicDays)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        file.setText("File");

        btnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSave.setText("Salva");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        file.add(btnSave);

        btnLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btnLoad.setText("Carica");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        file.add(btnLoad);

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnExit.setText("Esci");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        file.add(btnExit);

        menuBar.add(file);

        help.setText("Aiuto");

        github.setText("Github Repository");
        github.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubActionPerformed(evt);
            }
        });
        help.add(github);

        tutorial.setText("Guida");
        tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorialActionPerformed(evt);
            }
        });
        help.add(tutorial);

        bugReport.setText("Segnala un bug");
        bugReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugReportActionPerformed(evt);
            }
        });
        help.add(bugReport);

        btnCheckUpdate.setText("Cerca aggiornamenti");
        btnCheckUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUpdateActionPerformed(evt);
            }
        });
        help.add(btnCheckUpdate);

        menuBar.add(help);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Salva su file l'intero oggetto che contiene l'agoritmo e quindi le 2
     * liste.
     *
     * @param evt L'evento generato al clic sul pulsante di salvataggio.
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
            fc.setFileFilter(fileNameExtensionFilter);
            fc.showSaveDialog(this);
            File selecedFile = fc.getSelectedFile();
            if (selecedFile == null) {
                showMessage("Inserisci un nome per il file da salvare.", true);
                return;
            }
            FileManager.objectToFile(this.algorithm, selecedFile.getAbsolutePath() + ".gantt");
            showMessage("Salvataggio avvenuto con successo.", false);
        } catch (IOException ex) {
            showMessage("Errore nel salvataggio del file.", true);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * Carica da file l'intero oggetto che contiene l'agoritmo e quindi le 2
     * liste. Riempie la lista di dipendenze e la tabella.
     *
     * @param evt L'evento generato al clic sul pulsante di caricamento.
     */
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {
            JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
            fc.setFileFilter(fileNameExtensionFilter);
            fc.showOpenDialog(this);
            File selecedFile = fc.getSelectedFile();
            if (selecedFile == null) {
                showMessage("Seleziona un file da caricare.", true);
                return;
            }

            this.algorithm = (Algorithm) FileManager.fileToObject(selecedFile.getAbsolutePath());
            this.algorithm.getTasksESEF().forEach((t) -> {
                listModel.addElement(t.getName());
            });
            
            int cont = 0;
            int[] arr = new int[algorithm.getPublicDays().size()];
            for(DayOfWeek day : algorithm.getPublicDays())
                arr[cont++] = day.getValue() - 1;
            listPublicHolidays.setSelectedIndices(arr);
            
            showMessage("File caricato con successo.", false);
            realTimeRun();
        } catch (IOException | ClassNotFoundException ex) {
            showMessage("Errore nella lettura del file. Se non hai ancora salvato, fallo!", true);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * Chiude il programma.
     *
     * @param evt L'evento generato al clic sul pulsante di chiusura.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Apre nel browser predefinito la repository di Github.
     *
     * @param evt L'evento generato al clic sul pulsante di apertura di Github.
     */
    private void githubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubActionPerformed
        openBrowser("https://github.com/acerbisgianluca/Gantt-Project");
    }//GEN-LAST:event_githubActionPerformed

    /**
     * Apre nel browser predefinito la wiki del progetto su Github.
     *
     * @param evt L'evento generato al clic sul pulsante di apertura di Github.
     */
    private void tutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorialActionPerformed
        openBrowser("https://github.com/acerbisgianluca/Gantt-Project/wiki");
    }//GEN-LAST:event_tutorialActionPerformed

    /**
     * Apre nel browser predefinito gli issues del progetto su Github.
     *
     * @param evt L'evento generato al clic sul pulsante di apertura di Github.
     */
    private void bugReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugReportActionPerformed
        openBrowser("https://github.com/acerbisgianluca/Gantt-Project/issues");
    }//GEN-LAST:event_bugReportActionPerformed

    /**
     * Contiene l'algoritmo e i check per aggiungere/modificare un
     * {@link com.acerbisgianluca.ganttproject.utilities.Task}.
     *
     * @param evt L'evento generato al click del bottone per
     * aggiungere/modificare un
     * {@link com.acerbisgianluca.ganttproject.utilities.Task}.
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Task newESEF, newLSLF, tESEF, tLSLF;
        try {
            if (editing) {

                String name = txtName.getText().trim();
                if (name.equals("")) {
                    showMessage("Inserire il nome.", true);
                    return;
                }
                if (!this.lastName.equals(name)) {
                    taskExists(name);
                }

                newLSLF = algorithm.getTaskByName(this.lastName, false);
                newESEF = algorithm.getTaskByName(this.lastName, true);

                Date date = (Date) spnDate.getModel().getValue();
                LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                int[] dependenciesIds = listDependencies.getSelectedIndices();
                for (int i : dependenciesIds) {
                    if (i == 0 || listModel.getElementAt(i).equals(this.lastName)) {
                        continue;
                    }

                    if (algorithm.getTaskByName(listModel.getElementAt(i), true).getDependencies().contains(newESEF)) {
                        showMessage("Rilevato ciclo fra " + listModel.getElementAt(i) + " e " + name + " (nome precedente: " + this.lastName + ") attività.", true);
                        return;
                    }
                }
                for (int i : dependenciesIds) {
                    if (i == 0 || listModel.getElementAt(i).equals(this.lastName)) {
                        continue;
                    }

                    if (!newESEF.getDependencies().contains((tESEF = algorithm.getTaskByName(listModel.getElementAt(i), true)))) {
                        newESEF.addDependency(tESEF);
                        newLSLF.addDependency((tLSLF = algorithm.getTaskByName(listModel.getElementAt(i), false)));

                        tESEF.addParent(newESEF);
                        tLSLF.addParent(newLSLF);
                    }
                }

                if (isAdvanced) {
                    int a = (int) spnA.getModel().getValue() < 1 ? 1 : (int) spnA.getModel().getValue();
                    int m = (int) spnM.getModel().getValue() < 1 ? 1 : (int) spnM.getModel().getValue();
                    int b = (int) spnB.getModel().getValue() < 1 ? 1 : (int) spnB.getModel().getValue();
                    newLSLF.update(name, localDate, a, m, b, algorithm.getPublicDays());
                    newESEF.update(name, localDate, a, m, b, algorithm.getPublicDays());
                } else {
                    int duration = (int) spnDuration.getModel().getValue();
                    duration = duration < 1 ? 1 : duration;
                    newLSLF.update(name, localDate, duration, algorithm.getPublicDays());
                    newESEF.update(name, localDate, duration, algorithm.getPublicDays());
                }

                showResult();

                for (int i = 0; i < listModel.size(); i++) {
                    if (listModel.getElementAt(i).equals(this.lastName)) {
                        listModel.set(i, name);
                        break;
                    }
                }

                for (int i = 1; i < listModel.size(); i++) {
                    if (!listDependencies.isSelectedIndex(i)) {
                        if (newESEF.getDependencies().contains((tESEF = algorithm.getTaskByName(listModel.getElementAt(i), true)))) {
                            newESEF.removeDependency(tESEF);
                            newLSLF.removeDependency((tLSLF = algorithm.getTaskByName(listModel.getElementAt(i), false)));

                            tESEF.removeParent(newESEF);
                            tLSLF.removeParent(newLSLF);
                        }
                    }
                }

                cleanFields(false);
                realTimeRun();
                return;
            }

            String name = txtName.getText().trim();
            if (name.equals("")) {
                showMessage("Inserire il nome.", true);
                return;
            }
            taskExists(name);

            Date date = (Date) spnDate.getModel().getValue();
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (isAdvanced) {
                int a = (int) spnA.getModel().getValue() < 1 ? 1 : (int) spnA.getModel().getValue();
                int m = (int) spnM.getModel().getValue() < 1 ? 1 : (int) spnM.getModel().getValue();
                int b = (int) spnB.getModel().getValue() < 1 ? 1 : (int) spnB.getModel().getValue();
                newESEF = new Task(name, localDate, a, m, b, algorithm.getPublicDays());
                newLSLF = new Task(name, localDate, a, m, b, algorithm.getPublicDays());
            } else {
                int duration = (int) spnDuration.getModel().getValue();
                duration = duration < 1 ? 1 : duration;
                newESEF = new Task(name, localDate, duration, algorithm.getPublicDays());
                newLSLF = new Task(name, localDate, duration, algorithm.getPublicDays());
            }

            int[] dependenciesIds = listDependencies.getSelectedIndices();
            for (int i : dependenciesIds) {
                if (i == 0) {
                    continue;
                }

                tESEF = algorithm.getTaskByName(listModel.getElementAt(i), true);
                tLSLF = algorithm.getTaskByName(listModel.getElementAt(i), false);

                newESEF.addDependency(tESEF);
                newLSLF.addDependency(tLSLF);

                tESEF.addParent(newESEF);
                tLSLF.addParent(newLSLF);

            }

            algorithm.addTask(newESEF, true);
            algorithm.addTask(newLSLF, false);

            listModel.addElement(name);

            tableModel.addRow(new Object[]{name, newESEF.getDuration(), newESEF.getStart().format(this.fmt), newESEF.getEnd().format(this.fmt), newLSLF.getStart().format(this.fmt), newLSLF.getEnd().format(this.fmt)});
            cleanFields(false);
            realTimeRun();
        } catch (TaskNotFoundException | TaskAlreadyExistsException ex) {
            showMessage(ex.getMessage(), true);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * Elimina l'attività dalle liste, dalla tabella, dalla lista di dipendenze
     * e da tutte le attività ad essa collegate.
     *
     * @param evt L'evento generato al click sul bottone per eliminare
     * un'attività.
     */
    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed
        int row = table.getSelectedRow();
        String name = (String) table.getValueAt(row, 0);
        Task tESEF, tLSLF;
        try {
            tESEF = algorithm.getTaskByName(name, true);
            tLSLF = algorithm.getTaskByName(name, false);

            tESEF.getDependencies().forEach((t) -> {
                t.removeParent(tESEF);
            });
            tESEF.getParents().forEach((t) -> {
                t.removeDependency(tESEF);
            });
            tLSLF.getDependencies().forEach((t) -> {
                t.removeParent(tLSLF);
            });
            tLSLF.getParents().forEach((t) -> {
                t.removeDependency(tLSLF);
            });

            algorithm.removeFromLists(tESEF, tLSLF);
        } catch (TaskNotFoundException ex) {
            showMessage(ex.getMessage(), true);
        }

        tableModel.removeRow(row);
        listModel.removeElement(name);

        cleanFields(false);
        if (!this.algorithm.getTasksESEF().isEmpty()) {
            realTimeRun();
        }
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    /**
     * Elimina tutti i {@link com.acerbisgianluca.ganttproject.utilities.Task},
     * resetta la tabella e i campi.
     *
     * @param evt L'evento generato al click sul bottone per eliminare tutti i
     * {@link com.acerbisgianluca.ganttproject.utilities.Task}.
     */
    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        if (algorithm.getTasksESEF().isEmpty()) {
            showMessage("Non è stata ancora inserita alcuna attività.", true);
            return;
        }
        algorithm.resetLists();
        tableModel.setRowCount(0);
        listModel.clear();
        cleanFields(true);
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    /**
     * Carica nel form i dati del
     * {@link com.acerbisgianluca.ganttproject.utilities.Task} selezionato.
     *
     * @param evt L'evento generato al click su di una riga della tabella.
     */
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        editing = true;
        lblAddTask.setText("Modifica l'attività selezionata");
        btnAdd.setText("Modifica");
        btnDeleteTask.setEnabled(true);

        try {
            int row = table.getSelectedRow();
            String name = (String) table.getValueAt(row, 0);
            this.lastName = name;
            txtName.setText(name);
            spnDuration.setValue((int) table.getValueAt(row, 1));
            spnDate.setValue(java.sql.Date.valueOf(algorithm.getTaskByName(name, true).getDefaultDate()));
            Task tLSLF = algorithm.getTaskByName(name, false);
            if(tLSLF.isAdvanced()){
                spnA.setValue(tLSLF.getA());
                spnM.setValue(tLSLF.getM());
                spnB.setValue(tLSLF.getB());
            }
            List<Integer> selectedIndeces = new ArrayList<>();
            for (int i = 0; i < listModel.size(); i++) {
                for (int j = 0; j < tLSLF.getDependencies().size(); j++) {
                    if (tLSLF.getDependencies().get(j).getName().equals(listModel.getElementAt(i))) {
                        selectedIndeces.add(i);
                    }
                }
            }
            int[] selectedIndicesArr = new int[selectedIndeces.size()];
            int i = 0;
            for (Integer n : selectedIndeces) {
                selectedIndicesArr[i] = n;
                i++;
            }
            listDependencies.clearSelection();
            if (selectedIndeces.isEmpty()) {
                listDependencies.setSelectedIndex(0);
            } else {
                listDependencies.setSelectedIndices(selectedIndicesArr);
            }
        } catch (TaskNotFoundException ex) {
            showMessage(ex.getMessage(), true);
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * Blocca la propagazione del click delle frecce verso l'alto e il basso per
     * evitare bug con la tabella.
     *
     * @param evt L'evento generato al click di un tasto della tastiera.
     */
    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            evt.consume();
        }
    }//GEN-LAST:event_tableKeyPressed

    /**
     * Ottiene la versione attuale dal package e ne richiede il controllo. In
     * caso ci sia una nuova versione, chiede all'utente se vuole installarla.
     *
     * @param evt L'evento generato al click sul pulsante per controllare se ci
     * sono aggiornamenti.
     */
    private void btnCheckUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUpdateActionPerformed
        try {
            Package jarPackage = getClass().getPackage();
            boolean newVersion = VersionManager.checkVersion(jarPackage.getSpecificationVersion());
            if (newVersion) {
                if (JOptionPane.showConfirmDialog(this, "E' disponibile una nuova versione! Vuoi scaricarla?", "Versione corrente: " + jarPackage.getSpecificationVersion(), JOptionPane.YES_NO_OPTION) == 0) {
                    openBrowser("https://github.com/acerbisgianluca/Gantt-Project/releases/latest");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Stai già eseguendo l'ultima versione!", "Versione corrente: " + jarPackage.getSpecificationVersion(), JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (MalformedURLException | CannotCheckVersionException ex) {
            showMessage("Attualmente è impossibile controllare l'ultima versione rilasciata.", true);
        }
    }//GEN-LAST:event_btnCheckUpdateActionPerformed

    private void toggleAdvancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleAdvancedActionPerformed
        if (!this.isAdvanced) {
            toggleAdvanced.setText("Mod. normale");
            this.isAdvanced = true;
            spnDuration.setEnabled(false);
        } else {
            toggleAdvanced.setText("Mod. avanzata");
            this.isAdvanced = false;
            spnDuration.setEnabled(true);
        }
        toggleAdvanced();
    }//GEN-LAST:event_toggleAdvancedActionPerformed

    private void btnPublicDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicDaysActionPerformed
        List<DayOfWeek> list = new ArrayList<>();
        for(int i : listPublicHolidays.getSelectedIndices()){
            list.add(DayOfWeek.of(i + 1));
        }
        if(list.size() == 7){
            showMessage("Non è possibile selezionare tutti i giorni.", true);
            return;
        }
        algorithm.setPublicDays(list);
        realTimeRun();
    }//GEN-LAST:event_btnPublicDaysActionPerformed

    private void toggleAdvanced(){
        lblA.setEnabled(isAdvanced);
        lblM.setEnabled(isAdvanced);
        lblB.setEnabled(isAdvanced);
        spnA.setEnabled(isAdvanced);
        spnM.setEnabled(isAdvanced);
        spnB.setEnabled(isAdvanced);
        btnPublicDays.setEnabled(isAdvanced);
        listPublicHolidays.setEnabled(isAdvanced);
    }
    
    /**
     * Recupera il browser predefinito dell'utente e apre il link passato come
     * argomento.
     *
     * @param url L'url da aprire nel browser.
     */
    private void openBrowser(String url) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(new URL(url).toURI());
            } catch (IOException | URISyntaxException e) {
                showMessage("Impossibile aprire il browser.", true);
            }
        }
    }

    /**
     * Crea le righe all'interno della tabella indicando nome, durata, data di
     * inizio ES, data di fine EF, data di inizio LS e data di fine LF di ogni
     * attività.
     */
    public void showResult() {
        List<Task> esef = algorithm.getTasksESEF();
        List<Task> lslf = algorithm.getTasksLSLF();
        Task t, t1;
        tableModel.setRowCount(0);
        for (int i = 0; i < esef.size(); i++) {
            t = esef.get(i);
            t1 = lslf.get(i);
            tableModel.addRow(new Object[]{t.getName(), t.getDuration(), t.getStart().format(this.fmt), t.getEnd().format(this.fmt), t1.getStart().format(this.fmt), t1.getEnd().format(this.fmt), t1.isCritica() ? "Si" : "No", t.getEt(), t.getSd()});
        }
    }

    /**
     * Pulisce tutti i campi del form.
     *
     * @param starting Vero se l'applicazione è appena stata avviata, altrimenti
     * false.
     */
    private void cleanFields(boolean starting) {
        txtName.setText("");
        spnDuration.setValue(1);
        spnA.setValue(1);
        spnM.setValue(1);
        spnB.setValue(1);
        listPublicHolidays.clearSelection();
        spnDate.setValue(new Date());
        showMessage("", false);
        if (starting) {
            listModel.addElement("Nessuna");
        }
        listDependencies.setSelectedIndex(0);
        if (editing) {
            editing = false;
            lblAddTask.setText("Aggiungi una nuova attività");
            btnAdd.setText("Aggiungi");
            btnDeleteTask.setEnabled(false);
        }
    }

    /**
     * Controlla se un {@link com.acerbisgianluca.ganttproject.utilities.Task}
     * esiste già.
     *
     * @param name Il nome del nuovo
     * {@link com.acerbisgianluca.ganttproject.utilities.Task}.
     * @throws TaskAlreadyExistsException Se il
     * {@link com.acerbisgianluca.ganttproject.utilities.Task} esiste già lancia
     * la l'eccezione.
     */
    private void taskExists(String name) throws TaskAlreadyExistsException {
        for (Task t : algorithm.getTasksESEF()) {
            if (t.getName().equalsIgnoreCase(name)) {
                throw new TaskAlreadyExistsException("Un'attività con lo stesso nome esiste già.");
            }
        }
    }

    /**
     * Riesegue l'algoritmo sull'aggiunta o la modifica di un
     * {@link com.acerbisgianluca.ganttproject.utilities.Task}.
     */
    private void realTimeRun() {
        algorithm.resetForRunning();
        int totalDuration = algorithm.run();
        showMessage("La durata totale del ciclo di attività è di " + totalDuration + " giorni. Tempo previsto: " + algorithm.getTotalEt() + ". Deviazione standard: " + algorithm.getTotalSd() + ".", false);
        showResult();
    }

    /**
     * Imposta il comparatore per l'ordinamento delle colonne della tabella che
     * contengono una data.
     */
    private void setRowSorter() {
        TableRowSorter tableRowSorter = new TableRowSorter(tableModel);
        DateComparator dateComparator = new DateComparator();
        tableRowSorter.setComparator(2, dateComparator);
        tableRowSorter.setComparator(3, dateComparator);
        tableRowSorter.setComparator(4, dateComparator);
        tableRowSorter.setComparator(5, dateComparator);
        table.setRowSorter(tableRowSorter);
    }

    /**
     * Mostra il messaggio passato come argomento nella label posta sotto la
     * tabella.
     *
     * @param message Il messaggio da mostrare.
     * @param error Vero se è un errore, falso altrimenti.
     */
    private void showMessage(String message, boolean error) {
        if (error) {
            lblOutput.setForeground(Color.red);
        } else {
            lblOutput.setForeground(Color.black);
        }

        lblOutput.setText(message);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            App app = new App();
            URL url = App.class.getResource("/resources/img/logo.png");
            ImageIcon img = new ImageIcon(url);
            app.setIconImage(img.getImage());
            app.setVisible(true);
            System.setProperty("java.net.useSystemProxies", "true");
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JMenuItem btnCheckUpdate;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnLoad;
    private javax.swing.JButton btnPublicDays;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JMenuItem bugReport;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem github;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblAddTask;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblDependencies;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblPublicHolidays;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JList<String> listDependencies;
    private javax.swing.JList<String> listPublicHolidays;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JSeparator separator;
    private javax.swing.JSpinner spnA;
    private javax.swing.JSpinner spnB;
    private javax.swing.JSpinner spnDate;
    private javax.swing.JSpinner spnDuration;
    private javax.swing.JSpinner spnM;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JToggleButton toggleAdvanced;
    private javax.swing.JMenuItem tutorial;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
